generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: sourcehut.org
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 13 16:04:34 2026 GMT
  hsts: false
- host: man.sr.ht
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 26 19:16:50 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: git.sr.ht
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 20 00:01:40 2026 GMT
  hsts: true
  hsts_max_age: 31536000
domains:
- domain: sourcehut.org
  dnssec: false
  caa: []
  spf: true
  dmarc: true
  dmarc_policy: none
- domain: sr.ht
  dnssec: false
  caa: []
  spf: true
  dmarc: true
  dmarc_policy: none
